config/routes.rb
Rails.application.routes.draw do

  root "movies#index"

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies

  resources :genres

  resources :movies do
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end

  resource :session, only: [ :new, :create, :destroy]
  get "signin" => "sessions#new"

  resources :users
  get "signup" => "users#new"
end

app/models/movie.rb
class Movie < ApplicationRecord
  before_save :set_slug

  has_many :reviews, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :fans, through: :favorites, source: :user
  has_many :characterizations, dependent: :destroy
  has_many :genres, through: :characterizations

  validates :title, :released_on, :duration, presence: true

  validates :title, uniqueness: true

  validates :description, length: { minimum: 25 }

  validates :total_gross, numericality: { greater_than_or_equal_to: 0 }

  validate :acceptable_image

  has_one_attached :main_image

  RATINGS = %w(G PG PG-13 R NC-17)

  validates :rating, inclusion: { in: RATINGS }

  scope :released, -> { where("released_on < ?", Time.now).order("released_on desc") }
  scope :upcoming, -> { where("released_on > ?", Time.now).order("released_on asc") }
  scope :recent, -> (max = 5) { released.limit(max) }
  scope :flops, -> { released.where("total_gross < 225000000").order(total_gross: :desc) }
  scope :hits, -> { released.where("total_gross > 450000000").order(total_gross: :asc) }

  def average_stars
    reviews.average(:stars) || 0.0
  end

  def average_stars_as_percent
    (self.average_stars / 5.0) * 100.0
  end

  def flop?
    total_gross.blank? || total_gross < 225_000_000
  end

  def to_param
    slug
  end

  private

  def acceptable_image
    return unless main_image.present?

    unless main_image.blob.byte_size <= 1.megabyte
      errors.add(:main_image, "is too big")
    end

    acceptable_types = ["image/png", "image/jpg"]
    unless acceptable_types.include?(main_image.content_type)
      errors.add( :main_image, "not valid image type")
    end
  end

  def set_slug
    self.slug = title.parameterize
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :require_signin, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]
  before_action :set_movie, only: [:show, :update, :edit, :destroy]

  def index
    case params[:filter]
    when "upcoming"
      @movies = Movie.upcoming
    when "recent"
      @movies = Movie.recent
    when "flops"
      @movies = Movie.flops
    when "hits"
      @movies = Movie.hits
    else
      @movies = Movie.released
    end
  end

  def show
    @genres = @movie.genres.order(:name)
    @fans = @movie.fans
    if current_user
      @favorite = current_user.favorites.find_by(movie_id: @movie.id)
    end
  end

  def edit
  end

  def update
    if @movie.update(movie_params)
      redirect_to @movie, notice: "Movie successfully updated!"
    else
      render :edit
    end
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie, notice: "Movie successfully created!"
    else
      render :new
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_url, alert: "Movie successfully deleted!"
  end

  private

  def movie_params
    params.require(:movie).
      permit(:title, :description, :rating, :released_on, :total_gross,
             :director, :duration, :main_image, genre_ids: [])
  end

  def require_admin
  end

  def set_movie
    @movie = Movie.find_by!(slug: params[:id])
  end
end

app/helpers/movies_helper.rb
module MoviesHelper

  def average_stars(movie)
    if movie.average_stars.zero?
      content_tag(:strong, "No Reviews")
    else
      pluralize(number_with_precision(movie.average_stars, precision: 1), "star")
    end
  end

  def hit_or_flop(movie)
    if movie.flop?
      "FLOPOID!"
    else
      number_to_currency(movie.total_gross, precision: 0)
    end
  end

  def main_image(movie)
    if movie.main_image.attached?
      image_tag movie.main_image.variant(resize_to_limit: [150,nil] )
    else
      image_tag "placeholder.png"
    end
  end

  def year_of(movie)
    movie.released_on.strftime("%Y")
  end


end

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |f| %>
  <%= render "shared/errors", object: movie %>

  <%= f.label :title %>
  <%= f.text_field :title, autofocus: true %>

  <%= f.label :description %>
  <%= f.text_area :description, rows: 10 %>

  <%= f.label :rating %>
  <%= f.select :rating, Movie::RATINGS, prompt: "Pick one" %>

  <%= f.label :released_on %>
  <%= f.date_select :released_on, {}, {class: "date"} %>

  <%= f.label :total_gross %>
  <%= f.number_field :total_gross %>

  <%= f.label :director %>
  <%= f.text_field :director %>

  <%= f.label :duration %>
  <%= f.text_field :duration %>

  <%= f.label :main_image %>
  <%= f.file_field :main_image %>

  <%= f.label :categorizations %>
  <%= f.collection_check_boxes(:genre_ids, Genre.order(:name), :id, :name) %>

  <%= f.submit %>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing: <%= @movie.title %></h1>

<%= render "form", movie: @movie %>

app/views/movies/index.html.erb
<ul>
  <% @movies.each do |movie| %>
    <section class="movie">

      <div class="summary">
        <div class="image">
          <%= main_image(movie) %>
        </div>
        <h2><%= link_to(movie.title, movie_path(movie)) %></h2>
        <h5>Release Year: <%= year_of(movie) %> (<%= movie.rating %>)</h5>
        <span class="stars">
        <%= render "shared/stars", percent: movie.average_stars_as_percent %>
      </span>
      </div>
      <h3><%= hit_or_flop(movie) %></h3>
      <p><%= truncate(movie.description, length: 55, separator: ' ') %></p>
    </section>
  <% end %>
</ul>

<% if current_user_admin? %>
  <section class="admin">
    <%= link_to 'Add New Movie', new_movie_path, class: 'button' %>
  </section>
<% end %>

app/views/movies/new.html.erb
<h1>Create New Movie</h1>

<%= render "form", movie: @movie %>

app/views/movies/show.html.erb
<section class="movie-details">
  <div class="details">
    <h1><%= @movie.title %></h1>
    <div class="image">
      <%= main_image(@movie) %>
      <% if current_user %>
        <div class="faves">
          <%= fave_or_unfave_button(@movie, @favorite) %>
          <div class="count">
            <%= @fans.size %>
          </div>
        </div>
      <% end %>
    </div>
    <h2>
      <%= year_of(@movie) %> &bull; <%= @movie.rating %>
    </h2>
    <div class="reviews">
      <%= render "shared/stars", percent: @movie.average_stars_as_percent %>

      <%= link_to pluralize(@movie.reviews.size, "review"),
                  movie_reviews_path(@movie) %>
    </div>
    <h3>
      Director: <%= @movie.director %> &bull; Duration: <%= @movie.duration %>
    </h3>
    <p>
      <%= @movie.description %>
    </p>
    <table>
      <tr>
        <th>Total Gross:</th>
        <td><%= hit_or_flop(@movie) %></td>
      </tr>
    </table>
    <div><%= link_to "Write Review", new_movie_review_path(@movie), class: "review" %></div>
  </div>

  <aside>
    <% if @fans.present? %>
      <h4>Fans</h4>
      <ul>
        <% @fans.each do |user| %>
          <li>
            <%= link_to user.username, user %>
          </li>
        <% end %>
      </ul>
    <% end %>

    <% if @genres.present? %>
      <h4>Genres</h4>
      <ul>
        <% @genres.each do |genre| %>
          <li>
            <%= link_to genre.name, genre_path(genre) %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </aside>

</section>



<% if current_user_admin? %>
  <section class="admin">
    <%= link_to "Edit", edit_movie_path(@movie), class: "button" %>
    <%= link_to "Delete", movie_path(@movie), class: "button", method: :delete, data: { confirm: 'really?' } %>
  </section>
<% end %>