config/routes.rb
Rails.application.routes.draw do

  root "movies#index"

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies

  resources :genres

  resources :movies do
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end

  resource :session, only: [ :new, :create, :destroy]
  get "signin" => "sessions#new"

  resources :users
  get "signup" => "users#new"
end

app/views/layouts/_flash.html.erb
<%# if flash[:notice] %>
<!--  <div class="flash notice">-->
    <%#= flash[:notice] %>
<!--  </div>-->
<%# end %>

<%# if flash[:alert] %>
<!--  <div class="flash alert">-->
    <%#= flash[:alert] %>
<!--  </div>-->
<%# end %>

<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>footerie things go here</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <ul class="left">
      <li><%= link_to(image_tag("logo.png"), root_path) %></li>
      <li><%= link_to("All Movies", movies_path) %></li>
      <li><%= link_to("Upcoming", filtered_movies_path(:upcoming)) %></li>
      <li><%= link_to("Recent", filtered_movies_path(:recent)) %></li>
      <li><%= link_to("Hits", filtered_movies_path(:hits)) %></li>
      <li><%= link_to("Flops", filtered_movies_path(:flops)) %></li>
    </ul>
    <ul class="right">
      <% if current_user %>
        <ul><%= link_to current_user.name, current_user %></ul>
        <ul><%= link_to "Sign Out", session_path, method: :delete, class: "button" %></ul>
      <% else %>
        <li><%= link_to("Sign In", signin_path, class: "button") %></li>
        <li><%= link_to("Sign Up", signup_path, class: "button") %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flix</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<%= render "layouts/header" %>
<div>
  <%= render "layouts/flash" %>
</div>
<div class="content"><%= yield %></div>

<%= render "layouts/footer" %>

</body>
</html>